apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world-template
spec:
  entrypoint: say-hello
  templates:
    - name: say-hello
      container:
        image: alpine
        command: ["echo"]
        args: ["Hello from Argo!"]
